const users = [
  {
    "nombre": "Ana",
    "apellido": "García",
    "avatar": "URL imagen avatar",
    "mail": "ana.garcia@mail.com",
    "contraseña": "123456",
    "nombre_usuario": "ana.garcia",
    "type_account": "Admin",
    "notification": true,
    "activity": false
  },
  {
    "name": "Carlos",
    "last_name": "Martínez",
    "avatar": "URL imagen avatar",
    "mail": "carlos.martinez@mail.com",
    "password": "qwerty",
    "username": "carlos.martinez",
    "type_account": "Admin",
    "notification": true,
    "activity": false
  },
  {
    "name": "María",
    "last_name": "Sánchez",
    "avatar": "URL imagen avatar",
    "mail": "maria.sanchez@mail.com",
    "password": "password",
    "username": "maria.sanchez",
    "type_account": "Cliente",
    "notification": true,
    "activity": false
  },
  {
    "name": "Pedro",
    "last_name": "González",
    "avatar": "URL imagen avatar",
    "mail": "pedro.gonzalez@mail.com",
    "password": "abc123",
    "username": "pedro.gonzalez",
    "type_account": "Cliente",
    "notification": true,
    "activity": false
  },
  {
    "name": "Laura",
    "last_name": "Pérez",
    "avatar": "URL imagen avatar",
    "mail": "laura.perez@mail.com",
    "password": "secret",
    "username": "laura.perez",
    "type_account": "Cliente",
    "notification": true,
    "activity": false
  },
  {
    "name": "Santiago",
    "last_name": "Hernández",
    "avatar": "URL imagen avatar",
    "mail": "santiago.hernandez@mail.com",
    "password": "letmein",
    "username": "santiago.hernandez",
    "type_account": "Cliente",
    "notification": true,
    "activity": false
  },
  {
    "name": "Lucía",
    "last_name": "Romero",
    "avatar": "URL imagen avatar",
    "mail": "lucia.romero@mail.com",
    "password": "hello123",
    "username": "lucia.romero",
    "type_account": "Cliente",
    "notification": true,
    "activity": false
  },
  {
    "name": "Javier",
    "last_name": "Díaz",
    "avatar": "URL imagen avatar",
    "mail": "javier.diaz@mail.com",
    "password": "welcome",
    "username": "javier.diaz",
    "type_account": "Cliente",
    "notification": true,
    "activity": false
  },
  {
    "name": "Isabel",
    "last_name": "González",
    "avatar": "URL imagen avatar",
    "mail": "isabel.gonzalez@mail.com",
    "password": "123abc",
    "username": "isabel.gonzalez",
    "type_account": "Cliente",
    "notification": false,
    "activity": true
  },
  {
    "name": "Manuel",
    "last_name": "Martínez",
    "avatar": "URL imagen avatar",
    "mail": "manuel.martinez@mail.com",
    "password": "testing",
    "username": "manuel.martinez",
    "type_account": "Cliente",
    "notification": false,
    "activity": true
  },
  {
    "name": "Cristina",
    "last_name": "Santos",
    "avatar": "URL imagen avatar",
    "mail": "cristina.santos@mail.com",
    "password": "pass123",
    "username": "cristina.santos",
    "type_account": "Cliente",
    "notification": false,
    "activity": true
  },
  {
    "name": "Raúl",
    "last_name": "Fernández",
    "avatar": "URL imagen avatar",
    "mail": "raul.fernandez@mail.com",
    "password": "admin",
    "username": "raul.fernandez",
    "type_account": "Cliente",
    "notification": false,
    "activity": true
  },
  {
    "name": "Luisa",
    "last_name": "Gutiérrez",
    "avatar": "URL imagen avatar",
    "mail": "luisa.gutierrez@mail.com",
    "password": "test123",
    "username": "luisa.gutierrez",
    "type_account": "Cliente",
    "notification": false,
    "activity": true
  },
  {
    "name": "Juan",
    "last_name": "López",
    "avatar": "URL imagen avatar",
    "mail": "juan.lopez@mail.com",
    "password": "12345678",
    "username": "juan.lopez",
    "type_account": "Cliente",
    "notification": false,
    "activity": true
  },
  {
    "name": "Marta",
    "last_name": "García",
    "avatar": "URL imagen avatar",
    "mail": "marta.garcia@mail.com",
    "password": "p@ssword",
    "username": "marta.garcia",
    "type_account": "Cliente",
    "notification": false,
    "activity": true
  },
  {
    "name": "David",
    "last_name": "Hernández",
    "avatar": "URL imagen avatar",
    "mail": "david.hernandez@mail.com",
    "password": "admin123",
    "username": "david.hernandez",
    "type_account": "Cliente",
    "notification": false,
    "activity": true
  },
  {
    "name": "Silvia",
    "last_name": "González",
    "avatar": "URL imagen avatar",
    "mail": "silvia.gonzalez@mail.com",
    "password": "hello",
    "username": "silvia.gonzalez",
    "type_account": "Cliente",
    "notification": false,
    "activity": true
  },
  {
    "name": "Pablo",
    "last_name": "Rodríguez",
    "avatar": "URL imagen avatar",
    "mail": "pablo.rodriguez@mail.com",
    "password": "test",
    "username": "pablo.rodriguez",
    "type_account": "Cliente",
    "notification": true,
    "activity": false
  },
  {
    "name": "Marina",
    "last_name": "Pérez",
    "avatar": "URL imagen avatar",
    "mail": "marina.perez@mail.com",
    "password": "qwe123",
    "username": "marina.perez",
    "type_account": "Cliente",
    "notification": true,
    "activity": false
  },
  {
    "name": "Jorge",
    "last_name": "Sánchez",
    "avatar": "URL imagen avatar",
    "mail": "jorge.sanchez@mail.com",
    "password": "letmein123",
    "username": "jorge.sanchez",
    "type_account": "Cliente",
    "notification": true,
    "activity": false
  },
];
